---
language: python
services: docker

env:
  global:
    - ROLE_NAME: etiqa-flask-playbook
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

script:
  # Run tests.
  - cd etiqa-flask-playbook && molecule converge && ../ata-nodejs && molecule converge
