---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ata-nodejs
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

script:
  # Run tests.
  - molecule converge

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/