---

  - name: Install flask
    package:
      name: python-flask
      state: present 

  - name: Install git
    package:
      name: git
      state: present 

  - name: Install gunicorn via pip
    pip:
     executable: pip3
     name: gunicorn
