---
- hosts: all
  strategy: debug
  become: true

  tasks:
    - name: Include deployment playbook
      include: main.yml
  
  roles:
    - role: geerlingguy.mysql
      become: yes

    - role: redbeard28.pip3
      become: yes
